### ISSUE TITLE
ck-tensorflow/program/image-classification-tf-py/classify.py  is not executable.

### ISSUE THREAD

**Issue by taskset** [ctuning/ck-tensorflow#74]
$ ck run program:tensorflow --cmd_key=classify

* tensorflow (62de6ce26934e3eb)

OS CK UOA:            linux-64 (4258b5fe54828a50)

OS name:              Ubuntu 16.04.4 LTS
Short OS name:        Linux 4.15.0
Long OS name:         Linux-4.15.0-29-generic-x86_64-with-debian-stretch-sid
OS bits:              64
OS ABI:               x86_64

Platform init UOA:    -
***************************************************************************************
Current directory: /home/hello/CK/ck-tensorflow/program/tensorflow/tmp

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = lib-tensorflow (TensorFlow library):

    Resolved. CK environment UID = 28433f8d33a6f186

*** Dependency 2 = tensorflow-model (TensorFlow model (net and weights)):

    Resolved. CK environment UID = c8f9d4473da5995d (version 20151205)
  -----------------------------------

More than one dataset entry is found for this program:

0) image-jpeg-0001 (1aaaa23c44e588f9)
1) image-jpeg-dnn-cat (e496fdf046e6ac13)
2) image-jpeg-dnn-cat-gray (b6edb4314645efa0)
3) image-jpeg-dnn-computer-mouse (04df4936ba03c285)
4) image-jpeg-dnn-cropped-panda (0a4f26aa98034fd2)
5) image-jpeg-dnn-fish-bike (ebd96e7048ba3f7f)
6) image-jpeg-dnn-snake-224 (08d57fd1a6443ee9)
7) image-jpeg-dnn-surfers (b04c3400ba69fdc6)
8) image-jpeg-fgg (fgg, 21500da03e4ccfa3)

Select UOA (or press Enter for 0): 0

  Cleaning output files and directories:
    stderr.log
    stderr2.log
    stderr.log
    stderr2.log

***************************************************************************************
***************************************************************************************
Prepared script:

#! /bin/bash

. /home/hello/CK/local/env/28433f8d33a6f186/env.sh
. /home/hello/CK/local/env/c8f9d4473da5995d/env.sh

export CK_DATASET_PATH=/home/hello/CK/ctuning-datasets-min/dataset/image-jpeg-0001/

export BATCH_SIZE=5
export CK_DATASET_FILENAME=data.jpg
export NUM_BATCHES=5

echo    executing code ...
 ${CK_ENV_COMPILER_PYTHON_FILE} ../classify.py --model_dir=${CK_ENV_MODEL_TENSORFLOW} --image_file=/home/hello/CK/ctuning-datasets-min/dataset/image-jpeg-0001/data.jpg > stderr.log 2> stderr2.log

***************************************************************************************
  (bash -c "chmod 755 ./tmp-iIf2Zt.sh; . ./tmp-iIf2Zt.sh")

  (sleep 0.5 sec ...)

  (run ...)
executing code ...

 (printing output files) 

    * stderr2.log

      ./tmp-iIf2Zt.sh: line 15: ../classify.py: Permission denied
      

    * stderr.log

      

Execution time: 0.011 sec.

Program execution likely failed (return code 126 !=0 )!

we've check this file:
$ ls ck-tensorflow/program/image-classification-tf-py/ -lh
total 36K
-rwxrwxr-x 1 hello hello 8.9K 6月  29 21:24 benchmark.nvidia-gtx1080.py
-rwxrwxr-x 1 hello hello 8.9K 6月  29 21:24 benchmark.nvidia-tx1.py
-rw-rw-r-- 1 hello hello 6.5K 6月  29 21:24 classify.py
-rw-rw-r-- 1 hello hello 3.7K 6月  29 21:24 README.md

classify.py  is not  executable.

**Comment by psyhtest** [comment]
@w-simon Thanks for reporting! Let's try to fix this together.

In fact, `classify.py` shouldn't be executable. The problem is that `${CK_ENV_COMPILER_PYTHON_FILE}` is not defined on your environment, because Python is not explicitly set as a dependency if this program. I guess we usually don't see this error, because we often use TensorFlow built from source (which depends on Python so Python does get defined transitively). Let me check in a fix...

**Comment by gfursin** [comment]
Hi @w-simon . Thank you for reporting the problem - I reproduced it. @psyhtest correctly said that the problem is actually because Python is not detected when you automatically detected your TF via CK. I believe I fixed the problem and checked it on my machine with latest TF 1.9.0. Can you please do the following to test it:
```
$ ck pull all
$ ck rm env:28433f8d33a6f186 -f
$  ck run program:tensorflow --cmd_key=classify
```
These commands will update all repos including my fix, remove bad env with currently detected TF, and will let you to select a CK TensorFlow package (CPU or GPU) to be automatically installed by the CK. I tested with 1.9.0 cuda and it now worked on my machine ...
Thanks a lot!

**Comment by taskset** [comment]
@gfursin Thank you very much!
This had been fixed and working well.

**Comment by gfursin** [comment]
Great! Thanks @w-simon! Glad to hear that!
